default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: lunch-roulette_development

test:
  <<: *default
  database: lunch-roulette_test

production:
  <<: *default
  database: lunch-roulette_production
