# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 89796538477984e89247f6427418a8521ebd2fa308781b487126b9c732a52ae7dd37dec5e081b9109e368ca07f5d6ee7bbf7ff20d4da80f4acd34795a2782446

test:
  secret_key_base: 302b87ddc409090adf934a5d4fc7a1b5af19862b16628019c416ea95fb43e3d588b03e5f4bb916829dcebb159806dd9128102f14fa4fc93aab3d552606260289

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
